export const toggleActive = [
  { key: "0", text: "active", value: "active" },
  { key: "1", text: "inactive", value: "inactive" },
];
export const sortDirection = [
  { key: "0", text: "A-Z", value: "asc" },
  { key: "1", text: "Z-A", value: "desc" },
];

export const filterClientList = [
  { key: "0", text: "First Name", value: "firstName" },
  { key: "1", text: "Last Name", value: "lastName" },
  { key: "2", text: "Company", value: "companyName" },
  { key: "3", text: "Email", value: "email" },
  { key: "4", text: "Country", value: "country" },
];
export const filterCampaignList = [
  { key: "00", text: "Name", value: "name" },
  { key: "01", text: "Type", value: "type" },
  { key: "02", text: "Start", value: "startDate" },
  { key: "03", text: "End", value: "endDate" },
  { key: "04", text: "Status", value: "status" },
  // { key: "05", text: "Client", value: "client" },
  // { key: "06", text: "Agent", value: "agent" },
  { key: "07", text: "Length", value: "length" },
];

export const countries = [
  { text: "Afghanistan", key: "af", value: "Afghanistan", flag: "af" },
  { text: "Aland Islands", key: "ax", value: "Aland Islands", flag: "ax" },
  { text: "Albania", key: "al", value: "Albania", flag: "al" },
  { text: "Algeria", key: "dz", value: "Algeria", flag: "dz" },
  { text: "American Samoa", key: "as", value: "American Samoa", flag: "as" },
  { text: "Andorra", key: "ad", value: "Andorra", flag: "ad" },
  { text: "Angola", key: "ao", value: "Angola", flag: "ao" },
  { text: "Anguilla", key: "ai", value: "Anguilla", flag: "ai" },
  { text: "Antigua", key: "ag", value: "Antigua", flag: "ag" },
  { text: "Argentina", key: "ar", value: "Argentina", flag: "ar" },
  { text: "Armenia", key: "am", value: "Armenia", flag: "am" },
  { text: "Aruba", key: "aw", value: "Aruba", flag: "aw" },
  { text: "Australia", key: "au", value: "Australia", flag: "au" },
  { text: "Austria", key: "at", value: "Austria", flag: "at" },
  { text: "Azerbaijan", key: "az", value: "Azerbaijan", flag: "az" },
  { text: "Bahamas", key: "bs", value: "Bahamas", flag: "bs" },
  { text: "Bahrain", key: "bh", value: "Bahrain", flag: "bh" },
  { text: "Bangladesh", key: "bd", value: "Bangladesh", flag: "bd" },
  { text: "Barbados", key: "bb", value: "Barbados", flag: "bb" },
  { text: "Belarus", key: "by", value: "Belarus", flag: "by" },
  { text: "Belgium", key: "be", value: "Belgium", flag: "be" },
  { text: "Belize", key: "bz", value: "Belize", flag: "bz" },
  { text: "Benin", key: "bj", value: "Benin", flag: "bj" },
  { text: "Bermuda", key: "bm", value: "Bermuda", flag: "bm" },
  { text: "Bhutan", key: "bt", value: "Bhutan", flag: "bt" },
  { text: "Bolivia", key: "bo", value: "Bolivia", flag: "bo" },
  { text: "Bosnia", key: "ba", value: "Bosnia", flag: "ba" },
  { text: "Botswana", key: "bw", value: "Botswana", flag: "bw" },
  { text: "Bouvet Island", key: "bv", value: "Bouvet Island", flag: "bv" },
  { text: "Brazil", key: "br", value: "Brazil", flag: "br" },
  {
    text: "British Virgin Islands",
    key: "vg",
    value: "British Virgin Islands",
    flag: "vg",
  },
  { text: "Brunei", key: "bn", value: "Brunei", flag: "bn" },
  { text: "Bulgaria", key: "bg", value: "Bulgaria", flag: "bg" },
  { text: "Burkina Faso", key: "bf", value: "Burkina Faso", flag: "bf" },
  { text: "Burma", key: "mm", value: "Burma", flag: "mm", alias: "Myanmar" },
  { text: "Burundi", key: "bi", value: "Burundi", flag: "bi" },
  { text: "Caicos Islands", key: "tc", value: "Caicos Islands", flag: "tc" },
  { text: "Cambodia", key: "kh", value: "Cambodia", flag: "kh" },
  { text: "Cameroon", key: "cm", value: "Cameroon", flag: "cm" },
  { text: "Canada", key: "ca", value: "Canada", flag: "ca" },
  { text: "Cape Verde", key: "cv", value: "Cape Verde", flag: "cv" },
  { text: "Cayman Islands", key: "ky", value: "Cayman Islands", flag: "ky" },
  {
    text: "Central African Republic",
    key: "cf",
    value: "Central African Republic",
    flag: "cf",
  },
  { text: "Chad", key: "td", value: "Chad", flag: "td" },
  { text: "Chile", key: "cl", value: "Chile", flag: "cl" },
  { text: "China", key: "cn", value: "China", flag: "cn" },
  {
    text: "Christmas Island",
    key: "cx",
    value: "Christmas Island",
    flag: "cx",
  },
  { text: "Cocos Islands", key: "cc", value: "Cocos Islands", flag: "cc" },
  { text: "Colombia", key: "co", value: "Colombia", flag: "co" },
  { text: "Comoros", key: "km", value: "Comoros", flag: "km" },
  { text: "Congo", key: "cd", value: "Congo", flag: "cd" },
  {
    text: "Congo Brazzaville",
    key: "cg",
    value: "Congo Brazzaville",
    flag: "cg",
  },
  { text: "Cook Islands", key: "ck", value: "Cook Islands", flag: "ck" },
  { text: "Costa Rica", key: "cr", value: "Costa Rica", flag: "cr" },
  { text: "Cote Divoire", key: "ci", value: "Cote Divoire", flag: "ci" },
  { text: "Croatia", key: "hr", value: "Croatia", flag: "hr" },
  { text: "Cuba", key: "cu", value: "Cuba", flag: "cu" },
  { text: "Cyprus", key: "cy", value: "Cyprus", flag: "cy" },
  { text: "Czech Republic", key: "cz", value: "Czech Republic", flag: "cz" },
  { text: "Denmark", key: "dk", value: "Denmark", flag: "dk" },
  { text: "Djibouti", key: "dj", value: "Djibouti", flag: "dj" },
  { text: "Dominica", key: "dm", value: "Dominica", flag: "dm" },
  {
    text: "Dominican Republic",
    key: "do",
    value: "Dominican Republic",
    flag: "do",
  },
  { text: "Ecuador", key: "ec", value: "Ecuador", flag: "ec" },
  { text: "Egypt", key: "eg", value: "Egypt", flag: "eg" },
  { text: "El Salvador", key: "sv", value: "El Salvador", flag: "sv" },
  { text: "England", key: "gb eng", value: "England", flag: "gb  eng" },
  {
    text: "Equatorial Guinea",
    key: "gq",
    value: "Equatorial Guinea",
    flag: "gq",
  },
  { text: "Eritrea", key: "er", value: "Eritrea", flag: "er" },
  { text: "Estonia", key: "ee", value: "Estonia", flag: "ee" },
  { text: "Ethiopia", key: "et", value: "Ethiopia", flag: "et" },
  { text: "Europeanunion", key: "eu", value: "Europeanunion", flag: "eu" },
  {
    text: "Falkland Islands",
    key: "fk",
    value: "Falkland Islands",
    flag: "fk",
  },
  { text: "Faroe Islands", key: "fo", value: "Faroe Islands", flag: "fo" },
  { text: "Fiji", key: "fj", value: "Fiji", flag: "fj" },
  { text: "Finland", key: "fi", value: "Finland", flag: "fi" },
  { text: "France", key: "fr", value: "France", flag: "fr" },
  { text: "French Guiana", key: "gf", value: "French Guiana", flag: "gf" },
  {
    text: "French Polynesia",
    key: "pf",
    value: "French Polynesia",
    flag: "pf",
  },
  {
    text: "French Territories",
    key: "tf",
    value: "French Territories",
    flag: "tf",
  },
  { text: "Gabon", key: "ga", value: "Gabon", flag: "ga" },
  { text: "Gambia", key: "gm", value: "Gambia", flag: "gm" },
  { text: "Georgia", key: "ge", value: "Georgia", flag: "ge" },
  { text: "Germany", key: "de", value: "Germany", flag: "de" },
  { text: "Ghana", key: "gh", value: "Ghana", flag: "gh" },
  { text: "Gibraltar", key: "gi", value: "Gibraltar", flag: "gi" },
  { text: "Greece", key: "gr", value: "Greece", flag: "gr" },
  { text: "Greenland", key: "gl", value: "Greenland", flag: "gl" },
  { text: "Grenada", key: "gd", value: "Grenada", flag: "gd" },
  { text: "Guadeloupe", key: "gp", value: "Guadeloupe", flag: "gp" },
  { text: "Guam", key: "gu", value: "Guam", flag: "gu" },
  { text: "Guatemala", key: "gt", value: "Guatemala", flag: "gt" },
  { text: "Guinea", key: "gn", value: "Guinea", flag: "gn" },
  { text: "Guinea-Bissau", key: "gw", value: "Guinea-Bissau", flag: "gw" },
  { text: "Guyana", key: "gy", value: "Guyana", flag: "gy" },
  { text: "Haiti", key: "ht", value: "Haiti", flag: "ht" },
  { text: "Heard Island", key: "hm", value: "Heard Island", flag: "hm" },
  { text: "Honduras", key: "hn", value: "Honduras", flag: "hn" },
  { text: "Hong Kong", key: "hk", value: "Hong Kong", flag: "hk" },
  { text: "Hungary", key: "hu", value: "Hungary", flag: "hu" },
  { text: "Iceland", key: "is", value: "Iceland", flag: "is" },
  { text: "India", key: "in", value: "India", flag: "in" },
  {
    text: "Indian Ocean Territory",
    key: "io",
    value: "Indian Ocean Territory",
    flag: "io",
  },
  { text: "Indonesia", key: "id", value: "Indonesia", flag: "id" },
  { text: "Iran", key: "ir", value: "Iran", flag: "ir" },
  { text: "Iraq", key: "iq", value: "Iraq", flag: "iq" },
  { text: "Ireland", key: "ie", value: "Ireland", flag: "ie" },
  { text: "Israel", key: "il", value: "Israel", flag: "il" },
  { text: "Italy", key: "it", value: "Italy", flag: "it" },
  { text: "Jamaica", key: "jm", value: "Jamaica", flag: "jm" },
  {
    text: "Jan Mayen",
    key: "sj",
    value: "Jan Mayen",
    flag: "sj",
    alias: "Svalbard",
  },
  { text: "Japan", key: "jp", value: "Japan", flag: "jp" },
  { text: "Jordan", key: "jo", value: "Jordan", flag: "jo" },
  { text: "Kazakhstan", key: "kz", value: "Kazakhstan", flag: "kz" },
  { text: "Kenya", key: "ke", value: "Kenya", flag: "ke" },
  { text: "Kiribati", key: "ki", value: "Kiribati", flag: "ki" },
  { text: "Kuwait", key: "kw", value: "Kuwait", flag: "kw" },
  { text: "Kyrgyzstan", key: "kg", value: "Kyrgyzstan", flag: "kg" },
  { text: "Laos", key: "la", value: "Laos", flag: "la" },
  { text: "Latvia", key: "lv", value: "Latvia", flag: "lv" },
  { text: "Lebanon", key: "lb", value: "Lebanon", flag: "lb" },
  { text: "Lesotho", key: "ls", value: "Lesotho", flag: "ls" },
  { text: "Liberia", key: "lr", value: "Liberia", flag: "lr" },
  { text: "Libya", key: "ly", value: "Libya", flag: "ly" },
  { text: "Liechtenstein", key: "li", value: "Liechtenstein", flag: "li" },
  { text: "Lithuania", key: "lt", value: "Lithuania", flag: "lt" },
  { text: "Luxembourg", key: "lu", value: "Luxembourg", flag: "lu" },
  { text: "Macau", key: "mo", value: "Macau", flag: "mo" },
  { text: "Macedonia", key: "mk", value: "Macedonia", flag: "mk" },
  { text: "Madagascar", key: "mg", value: "Madagascar", flag: "mg" },
  { text: "Malawi", key: "mw", value: "Malawi", flag: "mw" },
  { text: "Malaysia", key: "my", value: "Malaysia", flag: "my" },
  { text: "Maldives", key: "mv", value: "Maldives", flag: "mv" },
  { text: "Mali", key: "ml", value: "Mali", flag: "ml" },
  { text: "Malta", key: "mt", value: "Malta", flag: "mt" },
  {
    text: "Marshall Islands",
    key: "mh",
    value: "Marshall Islands",
    flag: "mh",
  },
  { text: "Martinique", key: "mq", value: "Martinique", flag: "mq" },
  { text: "Mauritania", key: "mr", value: "Mauritania", flag: "mr" },
  { text: "Mauritius", key: "mu", value: "Mauritius", flag: "mu" },
  { text: "Mayotte", key: "yt", value: "Mayotte", flag: "yt" },
  { text: "Mexico", key: "mx", value: "Mexico", flag: "mx" },
  { text: "Micronesia", key: "fm", value: "Micronesia", flag: "fm" },
  { text: "Moldova", key: "md", value: "Moldova", flag: "md" },
  { text: "Monaco", key: "mc", value: "Monaco", flag: "mc" },
  { text: "Mongolia", key: "mn", value: "Mongolia", flag: "mn" },
  { text: "Montenegro", key: "me", value: "Montenegro", flag: "me" },
  { text: "Montserrat", key: "ms", value: "Montserrat", flag: "ms" },
  { text: "Morocco", key: "ma", value: "Morocco", flag: "ma" },
  { text: "Mozambique", key: "mz", value: "Mozambique", flag: "mz" },
  { text: "Namibia", key: "na", value: "Namibia", flag: "na" },
  { text: "Nauru", key: "nr", value: "Nauru", flag: "nr" },
  { text: "Nepal", key: "np", value: "Nepal", flag: "np" },
  { text: "Netherlands", key: "nl", value: "Netherlands", flag: "nl" },
  {
    text: "Netherlandsantilles",
    key: "an",
    value: "Netherlandsantilles",
    flag: "an",
  },
  { text: "New Caledonia", key: "nc", value: "New Caledonia", flag: "nc" },
  { text: "New Guinea", key: "pg", value: "New Guinea", flag: "pg" },
  { text: "New Zealand", key: "nz", value: "New Zealand", flag: "nz" },
  { text: "Nicaragua", key: "ni", value: "Nicaragua", flag: "ni" },
  { text: "Niger", key: "ne", value: "Niger", flag: "ne" },
  { text: "Nigeria", key: "ng", value: "Nigeria", flag: "ng" },
  { text: "Niue", key: "nu", value: "Niue", flag: "nu" },
  { text: "Norfolk Island", key: "nf", value: "Norfolk Island", flag: "nf" },
  { text: "North Korea", key: "kp", value: "North Korea", flag: "kp" },
  {
    text: "Northern Mariana Islands",
    key: "mp",
    value: "Northern Mariana Islands",
    flag: "mp",
  },
  { text: "Norway", key: "no", value: "Norway", flag: "no" },
  { text: "Oman", key: "om", value: "Oman", flag: "om" },
  { text: "Pakistan", key: "pk", value: "Pakistan", flag: "pk" },
  { text: "Palau", key: "pw", value: "Palau", flag: "pw" },
  { text: "Palestine", key: "ps", value: "Palestine", flag: "ps" },
  { text: "Panama", key: "pa", value: "Panama", flag: "pa" },
  { text: "Paraguay", key: "py", value: "Paraguay", flag: "py" },
  { text: "Peru", key: "pe", value: "Peru", flag: "pe" },
  { text: "Philippines", key: "ph", value: "Philippines", flag: "ph" },
  {
    text: "Pitcairn Islands",
    key: "pn",
    value: "Pitcairn Islands",
    flag: "pn",
  },
  { text: "Poland", key: "pl", value: "Poland", flag: "pl" },
  { text: "Portugal", key: "pt", value: "Portugal", flag: "pt" },
  { text: "Puerto Rico", key: "pr", value: "Puerto Rico", flag: "pr" },
  { text: "Qatar", key: "qa", value: "Qatar", flag: "qa" },
  { text: "Reunion", key: "re", value: "Reunion", flag: "re" },
  { text: "Romania", key: "ro", value: "Romania", flag: "ro" },
  { text: "Russia", key: "ru", value: "Russia", flag: "ru" },
  { text: "Rwanda", key: "rw", value: "Rwanda", flag: "rw" },
  { text: "Saint Helena", key: "sh", value: "Saint Helena", flag: "sh" },
  {
    text: "Saint Kitts and Nevis",
    key: "kn",
    value: "Saint Kitts and Nevis",
    flag: "kn",
  },
  { text: "Saint Lucia", key: "lc", value: "Saint Lucia", flag: "lc" },
  { text: "Saint Pierre", key: "pm", value: "Saint Pierre", flag: "pm" },
  { text: "Saint Vincent", key: "vc", value: "Saint Vincent", flag: "vc" },
  { text: "Samoa", key: "ws", value: "Samoa", flag: "ws" },
  { text: "San Marino", key: "sm", value: "San Marino", flag: "sm" },
  {
    text: "Sandwich Islands",
    key: "gs",
    value: "Sandwich Islands",
    flag: "gs",
  },
  { text: "Sao Tome", key: "st", value: "Sao Tome", flag: "st" },
  { text: "Saudi Arabia", key: "sa", value: "Saudi Arabia", flag: "sa" },
  { text: "Scotland", key: "gb  sct", value: "Scotland", flag: "gb  sct" },
  { text: "Senegal", key: "sn", value: "Senegal", flag: "sn" },
  { text: "Serbia", key: "cs", value: "Serbia", flag: "cs" },
  { text: "Serbia", key: "rs", value: "Serbia", flag: "rs" },
  { text: "Seychelles", key: "sc", value: "Seychelles", flag: "sc" },
  { text: "Sierra Leone", key: "sl", value: "Sierra Leone", flag: "sl" },
  { text: "Singapore", key: "sg", value: "Singapore", flag: "sg" },
  { text: "Slovakia", key: "sk", value: "Slovakia", flag: "sk" },
  { text: "Slovenia", key: "si", value: "Slovenia", flag: "si" },
  { text: "Solomon Islands", key: "sb", value: "Solomon Islands", flag: "sb" },
  { text: "Somalia", key: "so", value: "Somalia", flag: "so" },
  { text: "South Africa", key: "za", value: "South Africa", flag: "za" },
  { text: "South Korea", key: "kr", value: "South Korea", flag: "kr" },
  { text: "Spain", key: "es", value: "Spain", flag: "es" },
  { text: "Sri Lanka", key: "lk", value: "Sri Lanka", flag: "lk" },
  { text: "Sudan", key: "sd", value: "Sudan", flag: "sd" },
  { text: "Suriname", key: "sr", value: "Suriname", flag: "sr" },
  { text: "Swaziland", key: "sz", value: "Swaziland", flag: "sz" },
  { text: "Sweden", key: "se", value: "Sweden", flag: "se" },
  { text: "Switzerland", key: "ch", value: "Switzerland", flag: "ch" },
  { text: "Syria", key: "sy", value: "Syria", flag: "sy" },
  { text: "Taiwan", key: "tw", value: "Taiwan", flag: "tw" },
  { text: "Tajikistan", key: "tj", value: "Tajikistan", flag: "tj" },
  { text: "Tanzania", key: "tz", value: "Tanzania", flag: "tz" },
  { text: "Thailand", key: "th", value: "Thailand", flag: "th" },
  { text: "Timorleste", key: "tl", value: "Timorleste", flag: "tl" },
  { text: "Togo", key: "tg", value: "Togo", flag: "tg" },
  { text: "Tokelau", key: "tk", value: "Tokelau", flag: "tk" },
  { text: "Tonga", key: "to", value: "Tonga", flag: "to" },
  { text: "Trinidad", key: "tt", value: "Trinidad", flag: "tt" },
  { text: "Tunisia", key: "tn", value: "Tunisia", flag: "tn" },
  { text: "Turkey", key: "tr", value: "Turkey", flag: "tr" },
  { text: "Turkmenistan", key: "tm", value: "Turkmenistan", flag: "tm" },
  { text: "Tuvalu", key: "tv", value: "Tuvalu", flag: "tv" },
  {
    text: "U.A.E.",
    key: "ae",
    value: "U.A.E.",
    flag: "ae",
    alias: "United Arab Emirates",
  },
  { text: "Uganda", key: "ug", value: "Uganda", flag: "ug" },
  { text: "Ukraine", key: "ua", value: "Ukraine", flag: "ua" },
  {
    text: "United Kingdom",
    key: "gb",
    value: "United Kingdom",
    flag: "gb",
    alias: "uk",
  },
  {
    text: "United States",
    key: "us",
    value: "United States",
    flag: "us",
    alias: "America",
  },
  { text: "Uruguay", key: "uy", value: "Uruguay", flag: "uy" },
  {
    text: "US Minor Islands",
    key: "um",
    value: "US Minor Islands",
    flag: "um",
  },
  {
    text: "US Virgin Islands",
    key: "vi",
    value: "US Virgin Islands",
    flag: "vi",
  },
  { text: "Uzbekistan", key: "uz", value: "Uzbekistan", flag: "uz" },
  { text: "Vanuatu", key: "vu", value: "Vanuatu", flag: "vu" },
  { text: "Vatican City", key: "va", value: "Vatican City", flag: "va" },
  { text: "Venezuela", key: "ve", value: "Venezuela", flag: "ve" },
  { text: "Vietnam", key: "vn", value: "Vietnam", flag: "vn" },
  { text: "Wales", key: "gb wls", value: "Wales", flag: "gb  wls" },
  {
    text: "Wallis and Futuna",
    key: "wf",
    value: "Wallis and Futuna",
    flag: "wf",
  },
  { text: "Western Sahara", key: "eh", value: "Western Sahara", flag: "eh" },
  { text: "Yemen", key: "ye", value: "Yemen", flag: "ye" },
  { text: "Zambia", key: "zm", value: "Zambia", flag: "zm" },
  { text: "Zimbabwe", key: "zw", value: "Zimbabwe", flag: "zw" },
];

//
